const commercialSector = [
    { name: 'Tecnologías', value: 'Technologies' },
    { name: 'Agricultura', value: 'Agriculture' },
    { name: 'Alimentación y Bebidas', value: 'Food & Beverages' },
    { name: 'Automotriz', value: 'Automotive' },
    { name: 'Banca y Finanzas', value: 'Banking & Finance' },
    { name: 'Bienes Raíces', value: 'Real Estate' },
    { name: 'Construcción', value: 'Construction' },
    { name: 'Consultoría', value: 'Consulting' },
    { name: 'Educación', value: 'Education' },
    { name: 'Energía', value: 'Energy' },
    { name: 'Entretenimiento', value: 'Entertainment' },
    { name: 'Farmacéutico', value: 'Pharmaceutical' },
    { name: 'Gobierno y Sector Público', value: 'Government & Public Sector' },
    { name: 'Hotelería y Turismo', value: 'Hospitality & Tourism' },
    { name: 'Industria Textil', value: 'Textile Industry' },
    { name: 'Ingeniería', value: 'Engineering' },
    { name: 'Logística y Transporte', value: 'Logistics & Transportation' },
    { name: 'Manufactura', value: 'Manufacturing' },
    { name: 'Medios de Comunicación', value: 'Media & Communications' },
    { name: 'Minería', value: 'Mining' },
    { name: 'Moda y Retail', value: 'Fashion & Retail' },
    { name: 'Publicidad y Marketing', value: 'Advertising & Marketing' },
    { name: 'Química', value: 'Chemicals' },
    { name: 'Recursos Humanos', value: 'Human Resources' },
    { name: 'Salud y Medicina', value: 'Healthcare & Medicine' },
    { name: 'Seguros', value: 'Insurance' },
    { name: 'Servicios Ambientales', value: 'Environmental Services' },
    { name: 'Servicios Jurídicos', value: 'Legal Services' },
    { name: 'Servicios Personales', value: 'Personal Services' },
    { name: 'Telecomunicaciones', value: 'Telecommunications' },
    { name: 'Veterinaria', value: 'Veterinary' },
    { name: 'Vivienda y Urbanismo', value: 'Housing & Urban Development' },
    { name: 'Arte y Cultura', value: 'Art & Culture' },
    { name: 'Ciencias y Tecnología', value: 'Science & Technology' },
    { name: 'Deportes y Recreación', value: 'Sports & Recreation' },
    { name: 'Educación Superior', value: 'Higher Education' },
    { name: 'Electrónica', value: 'Electronics' },
    { name: 'Eventos y Congresos', value: 'Events & Conferences' },
    { name: 'Fintech', value: 'Fintech' },
    { name: 'Gestión Ambiental', value: 'Environmental Management' },
    { name: 'Hogar y Jardín', value: 'Home & Garden' },
    { name: 'Importación y Exportación', value: 'Import & Export' },
    { name: 'Ingeniería Civil', value: 'Civil Engineering' },
    { name: 'Ingeniería Mecánica', value: 'Mechanical Engineering' },
    { name: 'Investigación y Desarrollo', value: 'Research & Development' },
    { name: 'Joyería', value: 'Jewelry' },
    { name: 'Mantenimiento y Reparación', value: 'Maintenance & Repair' },
    { name: 'Minería y Extracción', value: 'Mining & Extraction' },
    { name: 'Productos de Consumo', value: 'Consumer Products' },
    { name: 'Publicidad Digital', value: 'Digital Advertising' },
    { name: 'Relaciones Públicas', value: 'Public Relations' },
    { name: 'Seguridad y Defensa', value: 'Security & Defense' },
    { name: 'Servicios Financieros', value: 'Financial Services' },
    { name: 'Servicios Técnicos', value: 'Technical Services' },
    { name: 'Tecnología de la Información', value: 'Information Technology' },
    { name: 'Transporte Aéreo', value: 'Air Transportation' },
    { name: 'Transporte Marítimo', value: 'Maritime Transportation' },
    { name: 'Transporte Terrestre', value: 'Land Transportation' },
    { name: 'Ventas y Distribución', value: 'Sales & Distribution' },
];

export { commercialSector };
