export * from './BannersFlat';
export * from './BeautyProducts';
export * from './BestSeller';
export * from './FeaturedProducts';
export * from './InformativeTags';
export * from './RandomProducts';
export * from './SwiperDedicatedCards';
export * from './TabsCategories';
export * from './CategorySlides';
